#!/bin/bash
yum install wget zip unzip -y
sudo yum install java-17-openjdk
wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.78/bin/apache-tomcat-9.0.78.tar.gz
tar -zvxf apache-tomcat-9.0.78.tar.gz
cd apache-tomcat-9.0.78/bin
chmod +x startup.sh
sh startup.sh
wget http://updates.jenkins.io/download/war/2.397/jenkins.war
cp jenkins.war/opt/tomcat/webapps
yum install git -y
